---
title: 종료 오류 | Microsoft Docs
ms.date: 09/13/2016
ms.openlocfilehash: 272e6cdd9a1da3cfd2e4f730f6aeb27577948278
ms.sourcegitcommit: 0907b8c6322d2c7c61b17f8168d53452c8964b41
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 08/05/2020
ms.locfileid: "87786393"
---
# <a name="terminating-errors"></a><span data-ttu-id="95ca2-102">종료 오류</span><span class="sxs-lookup"><span data-stu-id="95ca2-102">Terminating Errors</span></span>

<span data-ttu-id="95ca2-103">이 항목에서는 종료 오류를 보고 하는 데 사용 되는 방법에 대해 설명 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-103">This topic discusses the method used to report terminating errors.</span></span> <span data-ttu-id="95ca2-104">또한 cmdlet 내에서 메서드를 호출 하는 방법에 대해 설명 하 고, 메서드가 호출 될 때 Windows PowerShell 런타임에 의해 반환 될 수 있는 예외에 대해 설명 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-104">It also discusses how to call the method from within the cmdlet, and it discusses the exceptions that can be returned by the Windows PowerShell runtime when the method is called.</span></span>

<span data-ttu-id="95ca2-105">종료 오류가 발생 하면 cmdlet은 [Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) 메서드를 호출 하 여 오류를 보고 해야 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-105">When a terminating error occurs, the cmdlet should report the error by calling the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method.</span></span> <span data-ttu-id="95ca2-106">이 메서드를 사용 하면 cmdlet이 종료 오류를 발생 시킨 조건을 설명 하는 오류 레코드를 보낼 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-106">This method allows the cmdlet to send an error record that describes the condition that caused the terminating error.</span></span> <span data-ttu-id="95ca2-107">오류 레코드에 대 한 자세한 내용은 [Windows PowerShell 오류 레코드](./windows-powershell-error-records.md)를 참조 하십시오.</span><span class="sxs-lookup"><span data-stu-id="95ca2-107">For more information about error records, see [Windows PowerShell Error Records](./windows-powershell-error-records.md).</span></span>

<span data-ttu-id="95ca2-108">[Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) 메서드가 호출 되 면 Windows PowerShell 런타임은 파이프라인의 실행을 영구적으로 중지 하 고 [Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) 예외를 throw 합니다..</span><span class="sxs-lookup"><span data-stu-id="95ca2-108">When the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method is called, the  Windows PowerShell runtime permanently stops the execution of the pipeline and throws a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span> <span data-ttu-id="95ca2-109">[WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)또는 기타 몇 가지 api 호출을 수행 하려고 하면 이러한 호출로 인해 [Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) 예외가 throw 되는 경우를 발생 시킬 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-109">Any subsequent attempts to call [System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError), or several other APIs causes those calls to throw a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span>

<span data-ttu-id="95ca2-110">파이프라인의 다른 cmdlet이 종료 오류를 보고 하거나, 사용자가 파이프라인을 중지 하도록 요청 했거나, 어떤 이유로 완료 되기 전에 파이프라인이 중단 된 경우에도 [Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) 예외가 발생할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-110">The [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception can also occur if another cmdlet in the pipeline reports a terminating error, if the user has asked to stop the pipeline, or if the pipeline has been halted before completion for any reason.</span></span> <span data-ttu-id="95ca2-111">이 cmdlet은 오픈 리소스나 내부 상태를 정리 해야 하는 경우를 제외 하 고 [Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) 예외를 catch 하지 않아도 됩니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-111">The cmdlet does not need to catch the [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception unless it must clean up open resources or its internal state.</span></span>

<span data-ttu-id="95ca2-112">Cmdlet은 종료 오류를 보고 하기 전에 원하는 수의 출력 개체 또는 종료 되지 않는 오류를 기록할 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-112">Cmdlets can write any number of output objects or non-terminating errors before reporting a terminating error.</span></span> <span data-ttu-id="95ca2-113">그러나 종료 오류는 파이프라인을 영구적으로 중지 하며, 추가 출력, 종료 오류 또는 종료 되지 않는 오류를 보고할 수 없습니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-113">However, the terminating error permanently stops the pipeline, and no further output, terminating errors, or non-terminating errors can be reported.</span></span>

<span data-ttu-id="95ca2-114">Cmdlet은 [Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) 를 호출 하는 스레드에서만 [ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), 또는 [system.object](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) 입력 처리 메서드를 호출 하는 경우에만 호출 될 수 있습니다. 단,이 [작업을 수행](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)하는 것이 좋습니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-114">Cmdlets can call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) only from the thread that called the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) input processing method.</span></span> <span data-ttu-id="95ca2-115">다른 스레드에서 [Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) 또는 [WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) 을 호출 하려고 하지 마십시오. (영문)를 호출 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-115">Do not attempt to call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) or [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) from another thread.</span></span> <span data-ttu-id="95ca2-116">대신 오류를 주 스레드로 다시 전달 해야 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-116">Instead, errors must be communicated back to the main thread.</span></span>

<span data-ttu-id="95ca2-117">Cmdlet이 [ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)또는 [system.object](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) 의 구현에서 예외를 throw 할 수 [있습니다 (예](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)를 들어, cmdlet을 구현 하는 것이 가능 합니다.-).</span><span class="sxs-lookup"><span data-stu-id="95ca2-117">It is possible for a cmdlet to throw an exception in its implementation of the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) method.</span></span> <span data-ttu-id="95ca2-118">Windows PowerShell 호스트를 중지 하는 몇 가지 심각한 오류 조건을 제외 하 고 이러한 메서드에서 throw 되는 예외는 종료 오류로 해석 되어 Windows PowerShell 전체가 아니라 파이프라인을 중지 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-118">Any exception thrown from these methods (except for a few severe error conditions that stop the Windows PowerShell host) is interpreted as a terminating error which stops the pipeline, but not Windows PowerShell as a whole.</span></span> <span data-ttu-id="95ca2-119">이는 주 cmdlet 스레드에만 적용 됩니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-119">(This applies only to the main cmdlet thread.</span></span> <span data-ttu-id="95ca2-120">일반적으로 cmdlet에 의해 생성 된 스레드의 catch 되지 않은 예외는 Windows PowerShell 호스트를 중지 합니다. 오류 레코드는 오류 조건에 대 한 추가 정보를 제공 하기 때문에 예외를 throw 하는 대신 [Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) 를 사용 하는 것이 좋습니다 .이는 최종 사용자에 게 유용 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-120">Uncaught exceptions in threads spawned by the cmdlet, in general, halt the Windows PowerShell host.) We recommend that you use [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) rather than throwing an exception because the error record provides additional information about the error condition, which is useful to the end-user.</span></span> <span data-ttu-id="95ca2-121">Cmdlet은 모든 예외 ()를 catch 하 고 처리 하는 것에 대 한 관리 코드 지침을 따라야 합니다 `catch (Exception e)` .</span><span class="sxs-lookup"><span data-stu-id="95ca2-121">Cmdlets should honor the managed code guideline against catching and handling all exceptions (`catch (Exception e)`).</span></span> <span data-ttu-id="95ca2-122">알려진 형식과 예상 형식의 예외만 오류 레코드로 변환 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-122">Convert only exceptions of known and expected types into error records.</span></span>

## <a name="see-also"></a><span data-ttu-id="95ca2-123">참고 항목</span><span class="sxs-lookup"><span data-stu-id="95ca2-123">See Also</span></span>

[<span data-ttu-id="95ca2-124">System.object를 처리 합니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-124">System.Management.Automation.Cmdlet.BeginProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)

[<span data-ttu-id="95ca2-125">System.object..</span><span class="sxs-lookup"><span data-stu-id="95ca2-125">System.Management.Automation.Cmdlet.EndProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)

[<span data-ttu-id="95ca2-126">ProcessRecord입니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-126">System.Management.Automation.Cmdlet.ProcessRecord</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)

[<span data-ttu-id="95ca2-127">Pipelinestoppedexception.</span><span class="sxs-lookup"><span data-stu-id="95ca2-127">System.Management.Automation.Pipelinestoppedexception</span></span>](/dotnet/api/System.Management.Automation.PipelineStoppedException)

[<span data-ttu-id="95ca2-128">Throwterminatingerror \*입니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-128">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)

[<span data-ttu-id="95ca2-129">WriteError입니다.</span><span class="sxs-lookup"><span data-stu-id="95ca2-129">System.Management.Automation.Cmdlet.WriteError</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)

[<span data-ttu-id="95ca2-130">Windows PowerShell 오류 레코드</span><span class="sxs-lookup"><span data-stu-id="95ca2-130">Windows PowerShell Error Records</span></span>](./windows-powershell-error-records.md)

[<span data-ttu-id="95ca2-131">Writing a Windows PowerShell Cmdlet(Windows PowerShell Cmdlet 작성)</span><span class="sxs-lookup"><span data-stu-id="95ca2-131">Writing a Windows PowerShell Cmdlet</span></span>](./writing-a-windows-powershell-cmdlet.md)
